[[licensecheck]]
arch = "aarch64"
git-tree-sha1 = "e1184e1db90b985bcec2d65bc8cae187b59f6cfb"
os = "macos"

    [[licensecheck.download]]
    sha256 = "66f505552fbc1587500d1833824f5f5a7a44aa47eae99e22dd777789a085ffb7"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.aarch64-apple-darwin.tar.gz"
[[licensecheck]]
arch = "aarch64"
git-tree-sha1 = "94c9fd3bb23f6f27767ec7bf1f72a66b708ee64b"
libc = "glibc"
os = "linux"

    [[licensecheck.download]]
    sha256 = "48669b94e65af77948ffe641c148bbe582c06463f449838d032005ce3a561fb9"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.aarch64-linux-gnu.tar.gz"
[[licensecheck]]
arch = "aarch64"
git-tree-sha1 = "a3a2f560a6e5a20ea5b3c2aa0a9d5880b65c1973"
libc = "musl"
os = "linux"

    [[licensecheck.download]]
    sha256 = "c51e545305a2ac8e03cab481008c643362034f62f292992bfbcfaafaad3f79d2"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.aarch64-linux-musl.tar.gz"
[[licensecheck]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "79c384dfb173afe7fc918d25bb9a33024d984c52"
libc = "glibc"
os = "linux"

    [[licensecheck.download]]
    sha256 = "04ed9662d93c2ad21004f37210dd7bf63b3026ae7355b95a6d8dce1f1200dfa2"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.armv6l-linux-gnueabihf.tar.gz"
[[licensecheck]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d94c4a3208f12f2dc12cad20fceac11b1c98e69"
libc = "musl"
os = "linux"

    [[licensecheck.download]]
    sha256 = "d735e733ec9f90cb6fb125960269ac89267f8b63741d65580a07f73fc132cf07"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.armv6l-linux-musleabihf.tar.gz"
[[licensecheck]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b836cecbe69fd11ba156de1b4bfe2f138f008f83"
libc = "glibc"
os = "linux"

    [[licensecheck.download]]
    sha256 = "69f65e1cc9a9d87b240752df2eb016f4c5e41811bc3468424fc7386f3c89ee5d"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[licensecheck]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ce95d001a77dbc0924986d0d64db252baafaeaa"
libc = "musl"
os = "linux"

    [[licensecheck.download]]
    sha256 = "681892b2c8913930f7a0277e2aec9c45a2bb1afd308d98240f892682069d67fe"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.armv7l-linux-musleabihf.tar.gz"
[[licensecheck]]
arch = "i686"
git-tree-sha1 = "7205725a4712a468a5f41aaa0a7da69844eb62c0"
libc = "glibc"
os = "linux"

    [[licensecheck.download]]
    sha256 = "d3bae10d32215844ef850b45d8d89a3278b403c525d82790ad3d372f02365403"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.i686-linux-gnu.tar.gz"
[[licensecheck]]
arch = "i686"
git-tree-sha1 = "96de6975029a5874dbe19b1b2ef8ba3352f1b098"
libc = "musl"
os = "linux"

    [[licensecheck.download]]
    sha256 = "429eb024c167635c4bdb8f241c5101eb5823502ea04a9e9d47734d6bb7a9274f"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.i686-linux-musl.tar.gz"
[[licensecheck]]
arch = "i686"
git-tree-sha1 = "a4ca96ce7f8f795dd3a68ef0f60e11fa4007cc2f"
os = "windows"

    [[licensecheck.download]]
    sha256 = "65dc47b17db6d90733612061d9a702a5a14b115bfdf5f0d350e9fb2d65edaeab"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.i686-w64-mingw32.tar.gz"
[[licensecheck]]
arch = "powerpc64le"
git-tree-sha1 = "9af8e2ae61dd9bfc92cd5c40904fed861acd29ab"
libc = "glibc"
os = "linux"

    [[licensecheck.download]]
    sha256 = "8c3bc633e04ed738a943f0bdc183d187141a8784d8d8ea147fc74dd4af003ca8"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[licensecheck]]
arch = "riscv64"
git-tree-sha1 = "44814667d9dfd7d6dbe3b798af578c5c3e97469c"
libc = "glibc"
os = "linux"

    [[licensecheck.download]]
    sha256 = "b9f8ee66d762d843f47066f450d229fffed5cc2ddb2594006b7b7d3a25849ba8"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.riscv64-linux-gnu.tar.gz"
[[licensecheck]]
arch = "x86_64"
git-tree-sha1 = "a56c4598e9c8b9d39990a13b368b060e4999e29d"
os = "macos"

    [[licensecheck.download]]
    sha256 = "454a8b5e1f8d415b5358ca7a00b9ab7c02c997c26a7e722b1250c4708e8a71d8"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.x86_64-apple-darwin.tar.gz"
[[licensecheck]]
arch = "x86_64"
git-tree-sha1 = "7222b8dc23bc7a789496a773eee0e04e64591da9"
libc = "glibc"
os = "linux"

    [[licensecheck.download]]
    sha256 = "df4d8765b618f28436323f4f2e9a08bf8e18e4ba2edbaa383b1eecc4ae327642"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.x86_64-linux-gnu.tar.gz"
[[licensecheck]]
arch = "x86_64"
git-tree-sha1 = "10db3ec28bb3b0ecfef1467bd5e12aa36eab827a"
libc = "musl"
os = "linux"

    [[licensecheck.download]]
    sha256 = "b0b83cc38cbc2d3b242ff5c918ab79da7c8705bbaafc881bf99478f7d822d006"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.x86_64-linux-musl.tar.gz"
[[licensecheck]]
arch = "x86_64"
git-tree-sha1 = "32c55b6378496c934ac0b096ffa980ac96739423"
os = "freebsd"

    [[licensecheck.download]]
    sha256 = "9c6fa72cfbf337978ad498a5148facc527c55fe5010c5bd77506d19d198435d4"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.x86_64-unknown-freebsd.tar.gz"
[[licensecheck]]
arch = "x86_64"
git-tree-sha1 = "855a823463881ae0d02d857a51b0e3ff3d82b421"
os = "windows"

    [[licensecheck.download]]
    sha256 = "3630a164c587e8cf6ff2c0ee2bbcbdefae179ff787d6381b1acdd68b74a402e8"
    url = "https://github.com/JuliaBinaryWrappers/licensecheck_jll.jl/releases/download/licensecheck-v0.4.0+0/licensecheck.v0.4.0.x86_64-w64-mingw32.tar.gz"
